// Generated by dts-bundle-generator v9.5.1

declare function base64Decode(input: string): Uint8Array;
declare function base64Encode(input: Uint8Array): string;
declare function lockForm(inputIds: string[], submitId: string, formErrorId: string): Map<string, string>;
declare function setFormInputErrors(inputIdMap: Map<string, string>, formErrorId: string, problems: {
	pointer: string | null;
	detail: string | null;
}[] | null, formErrorPrefix: string): void;
declare function setFormError(formErrorId: string, error: string): void;
declare function unlockForm(inputIds: string[], submitId: string): void;

declare namespace form {
	export { lockForm, setFormError, setFormInputErrors, unlockForm };
}
declare namespace base64 {
	export { base64Decode, base64Encode };
}

export {
	base64,
	form,
};

export {};
